# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='task_status',
            field=models.IntegerField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('MISSED', 'Missed')], default=0),
        ),
    ]
