# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180304_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='task_status',
            field=models.IntegerField(default=1, verbose_name=((1, 'Pending'), (2, 'Done'), (3, 'Missed'))),
        ),
    ]
