# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180304_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='task_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Missed')], default=1, max_length=10),
        ),
    ]
